hl.on("hyprland.start", function()
    hl.exec_cmd("uwsm app -- nm-applet")
    hl.exec_cmd("uwsm app -- waybar")
    hl.exec_cmd("uwsm app -- ie-r")
    hl.exec_cmd("uwsm app -- 1password --silent")
end)
